def remote = [:]
remote.name = "node-1"
remote.host = "<IP_ADDRESS>"

remote.allowAnyHosts = true
// create credential in Jenkins for EC2 container with id of AWS-EC2 using private key for the container
node {
  withCredentials([sshUserPrivateKey(credentialsId: 'AWS-EC2', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'username')]) {
    remote.user = username
    remote.identityFile = identity
    stage("SSH Steps Rocks!") {
      sshPut remote: remote, from: 'deploy.sh', into: '/wordle/jenkins-docker/Deploy/'
      sshScript remote: remote, script: "deploy.sh"
    }
  }
}