version: '3'
services:
  redis:
    image: redis:alpine
    container_name: 'redis-container'
    ports:
      - "6379:6379"
  # cron:
  #   image: cron-alpine
  #   container_name: 'cron-container'
  #   volumes:
  #     - ./var:/wordle/var
  #   ports:
  #     - "9500:9500"
    
  stats:
    build: .
    container_name: 'stats-container'
    ports: 
      - "9000:9000"
    volumes:
      - ./var:/wordle/var
    depends_on:
      - redis
  wordcheck:
    build: .
    container_name: 'wordcheck-container'
    ports: 
      - "9100:9100"
    volumes:
      - ./var:/wordle/var
  wordvalidation:
    build: .
    container_name: 'wordvalidation-container'
    ports: 
      - "9200:9200"
    volumes:
      - ./var:/wordle/var
  play:
    build: .
    container_name: 'play-container'
    ports: 
      - "9300:9300"
    volumes:
      - ./var:/wordle/var
  orchestrator:
    build: .
    container_name: 'orchestrator-container'
    ports: 
      - "9400:9400"
    volumes:
      - ./var:/wordle/var
    depends_on:
      - stats
      - wordcheck
      - wordvalidation
      - play
