version: '3'
services:
  redis:
    image: redis:alpine
    container_name: 'redis-cont'
    # command: ash -c "redis-server --appendonly yes --requirepass password"
    command: redis-server /etc/redis.conf # this file has password and other configs
    ports:
      - "6379:6379" # need to map it to a port on the host so crontab can update it with the top streaks and wins
    volumes:
      - ./var/redis:/data     # add volume to persist data between container restarts
      - ./redis.conf:/etc/redis.conf  # don't forget to import the config file
    restart: unless-stopped
  stats:
    build: ./app/services/Stats     # build image automatically from Dockerfile
    # image: w-stats    # must build image manually first
    container_name: 'stats-cont'
    ports: 
      - "9000:9000"
    volumes:
      - db:/wordle/var
      - .env:/wordle/.env
    depends_on:
      - redis
    restart: unless-stopped
  wordcheck:
    build: ./app/services/WordCheck
    # image: w-check
    container_name: 'check-cont'
    ports: 
      - "9100:9100"
    volumes:
      - db:/wordle/var
    restart: unless-stopped
  wordvalidation:
    build: ./app/services/WordValidation
    # image: w-validation
    container_name: 'validation-cont'
    ports: 
      - "9200:9200"
    volumes:
      - db:/wordle/var
    restart: unless-stopped
  play:
    build: ./app/services/Play
    # image: w-play
    container_name: 'play-cont'
    ports: 
      - "9300:9300"
    volumes:
      - db:/wordle/var
      - .env:/wordle/.env
    restart: unless-stopped
  orchestrator:
    build: .
    # image: w-orc
    container_name: 'orc-cont'
    ports: 
      - "9400:9400"
    volumes:
      - db:/wordle/var
      - ./.env:/wordle/.env
    depends_on:
      - stats
      - wordcheck
      - wordvalidation
      - play
    restart: unless-stopped
volumes:
  db:
