version: '3'
services:
  redis:
    image: redis:alpine
    container_name: 'redis-cont'
    ports:
      - "6379:6379"
  stats:
    # build: .
    image: w-stats
    container_name: 'stats-container'
    ports: 
      - "9000:9000"
    volumes:
      - db:/wordle/var
    depends_on:
      - redis
  wordcheck:
    # build: .
    image: w-check
    container_name: 'check-cont'
    ports: 
      - "9100:9100"
    volumes:
      - db:/wordle/var
  wordvalidation:
    # build: .
    image: w-validation
    container_name: 'validation-cont'
    ports: 
      - "9200:9200"
    volumes:
      - db:/wordle/var
  play:
    # build: .
    image: w-play
    container_name: 'play-cont'
    ports: 
      - "9300:9300"
  orchestrator:
    # build: .
    image: w-orc
    container_name: 'orc-cont'
    ports: 
      - "9400:9400"
    volumes:
      - db:/wordle/var
    depends_on:
      - stats
      - wordcheck
      - wordvalidation
      - play
volumes:
  db:
